### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by viddo** [MetaMad/metamap#1]
- [ ] import sample datasets -http://datos.madrid.es/portal/site/egob/menuitem.9e1e2f6404558187cf35cf3584f1a5a0/?vgnextoid=374512b9ace9f310VgnVCM100000171f5a0aRCRD
- [ ] create trigger function to generate convex hull from dataset (trigger on data change), update geom in metadata table

navigate map:
- [ ] add search box for address
- [ ] location API to get current location of user?

browse data:
- [ ] add filters for metadata?

other:
- [ ] about box

**Comment by viddo** [comment]
@javierarce :point_up:

**Comment by javierarce** [comment]
### Creating a trigger and function in CartoDB
http://stackoverflow.com/questions/25372592/creating-a-trigger-and-function-in-cartodb

#### ConvexHull
http://postgis.net/docs/ST_ConvexHull.html

**Comment by viddo** [comment]
query to generate polygons in buckets per district, and update the metadata table (here using `table_009crucessemaforizadosbici` as source):

```
WITH p_and_d AS (
  SELECT p.the_geom AS the_geom, d.nombre AS district
  FROM table_009crucessemaforizadosbici p, distritos AS d
  WHERE ST_Intersects(p.the_geom, d.the_geom) GROUP BY p.the_geom, district
),
pb AS (SELECT district, ST_ConcaveHull(ST_Collect(the_geom), 0.99, true) AS the_geom FROM p_and_d GROUP BY district),
upsert AS (UPDATE metamap SET the_geom=pb.the_geom, district=pb.district FROM pb WHERE dataset_id='table_009crucessemaforizadosbici' RETURNING *)
INSERT INTO metamap (the_geom, district, dataset_id) SELECT pb.the_geom, pb.district, 'table_009crucessemaforizadosbici' FROM pb WHERE NOT EXISTS (SELECT * FROM upsert);

WITH p_and_d AS (
  SELECT p.the_geom AS the_geom, d.nombre AS district
  FROM table_216619_0_wifi_municipal p, distritos AS d
  WHERE ST_Intersects(p.the_geom, d.the_geom) GROUP BY p.the_geom, district
),
pb AS (SELECT district, ST_ConcaveHull(ST_Collect(the_geom), 0.99, true) AS the_geom FROM p_and_d GROUP BY district),
upsert AS (UPDATE metamap SET the_geom=pb.the_geom, district=pb.district FROM pb WHERE dataset_id='table_216619_0_wifi_municipal' RETURNING *)
INSERT INTO metamap (the_geom, district, dataset_id) SELECT pb.the_geom, pb.district, 'table_216619_0_wifi_municipal' FROM pb WHERE NOT EXISTS (SELECT * FROM upsert);


WITH p_and_d AS (
  SELECT p.the_geom AS the_geom, d.nombre AS district
  FROM table_216619_0_wifi_municipal p, distritos AS d
  WHERE ST_Intersects(p.the_geom, d.the_geom) GROUP BY p.the_geom, district
),
pb AS (SELECT district, ST_ConcaveHull(ST_Collect(the_geom), 0.99, true) AS the_geom FROM p_and_d GROUP BY district),
upsert AS (UPDATE metamap SET the_geom=pb.the_geom, district=pb.district FROM pb WHERE dataset_id='table_216619_0_wifi_municipal' RETURNING *)
INSERT INTO metamap (the_geom, district, dataset_id) SELECT pb.the_geom, pb.district, 'table_216619_0_wifi_municipal' FROM pb WHERE NOT EXISTS (SELECT * FROM upsert);
```

**Comment by javierarce** [comment]
Fill given extent with a rectangular coverage: 
https://github.com/CartoDB/cartodb-postgresql/wiki/CDB_RectangleGrid
